catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBookListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books/create/', views.BookCreate.as_view(), name='book-create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('borrow/<uuid:pk>', views.borrow_book, name='book_borrow'),
    path('avilable/', views.AvilableBooksListView.as_view(), name='avilable_books'),
    path('return/<uuid:pk>', views.return_book, name='book_return'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(), name='bookinstance-create'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from datetime import date
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:genre-detail', args=[str(self.id)])
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.last_name + ', ' + self.first_name
    
    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=[str(self.id)])
    
class Language(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT, related_name = 'books')
    summary = models.TextField(max_length=1000)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField( max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability', )
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='borrower')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),("can_see_all_borrowed", "See all borrowed books"))

    def __str__(self):
        return f'{self.book.title} ({self.id})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              {% if user.is_authenticated %}
                  User: {{ user.username }}
                  {% if user.is_superuser %}(Admin) {%else%}({{ user.groups.all.0.name }}) {% endif %}
              {%endif%}
              <li><a href="{% url 'catalog:index' %}">Home</a></li>
              <li><a href="{% url 'catalog:books' %}">All books</a></li>
              <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
              <li><a href="{% url 'catalog:avilable_books' %}">Avilable books</a></li>
              <li></li>
              <li></li>
              {% if user.is_authenticated %}
                  <li>
                    <a href="{% url 'catalog:my-borrowed' %}">My borrowed books</a>
                  </li>
                  
                  {% if perms.catalog.can_see_all_borrowed %}
                    <li>
                      <a href="{% url 'catalog:all-borrowed' %}">All Borrowed Books</a>
                    </li>
                  {% endif %}
                  {% if perms.catalog.add_author %}
                    <li>
                      <a href="{% url 'catalog:author-create' %}">Add Author</a>
                    </li>
                  {% endif %}
                  {% if perms.catalog.add_book %}
                    <li>
                      <a href="{% url 'catalog:book-create' %}">Add Book</a>
                    </li>
                  {% endif %}
                  {% if perms.catalog.add_bookinstance %}
                    <li>
                      <a href="{% url 'catalog:bookinstance-create' %}">Create BookInstance</a>
                    </li>
                  {% endif %}
                  {% if user.is_superuser %}
                    <li>
                      <a href="{% url 'admin:index' %}">Add Librarian</a>
                    </li>
                  {% endif %}
                  <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-link" type="submit">Log Out</button>
                    </form>
                  </li>
                  
              {% else %}
                  <li>
                  <a href="{% url 'login' %}">Log In</a>
                  </li>
              {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
              </div>
            {% endif %}
          {% endblock %}
        </div>
        
      </div>
    </div>
  </body>
</html>