catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBookListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books/create/', views.BookCreate.as_view(), name='book-create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('borrow/<uuid:pk>', views.borrow_book, name='book_borrow'),
    path('avilable/', views.AvilableBooksListView.as_view(), name='avilable_books'),
    path('return/<uuid:pk>', views.return_book, name='book_return'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(), name='bookinstance-create'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from datetime import date
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:genre-detail', args=[str(self.id)])
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.last_name + ', ' + self.first_name
    
    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=[str(self.id)])
    
class Language(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT, related_name = 'books')
    summary = models.TextField(max_length=1000)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField( max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability', )
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='borrower')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),("can_see_all_borrowed", "See all borrowed books"))

    def __str__(self):
        return f'{self.book.title} ({self.id})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from catalog.models import Author, Book, BookInstance

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError('Invalid date - renewal in past')

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Invalid date - renewal more than 4 weeks ahead')
        return data
    
# author class that inherit from modelform
class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'date_of_birth': 'Date of Birth', 'date_of_death': 'Date of Death'}
        widgets = {'date_of_birth': forms.DateInput({'type': 'date'}), 'date_of_death': forms.DateInput({'type': 'date'})}
    
    # check if date_of_birth is less than date_of_death
    def clean_date_of_death(self):
        data = self.cleaned_data['date_of_death']
        # check if data is not null
        if data is None:
            return data
        # check if date_of_birth is less than date_of_death
        if data < self.cleaned_data['date_of_birth']:
            raise ValidationError('Invalid date - death date before birth date')
        # check if it is the same dob and dod
        if data == self.cleaned_data['date_of_birth']:
            raise ValidationError('Invalid date - death date is the same as birth date')
        return data

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']

class BookInstanceForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'imprint', 'status']
        widgets = {'due_back': forms.DateInput({'type': 'date'})}

catalog/views.py
import datetime
from typing import Any
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from catalog.forms import AuthorForm, BookForm, BookInstanceForm, RenewBookForm
from .models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin
# import generic view from django
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
# import createview
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Count


# Create your views here.

def index(request: HttpRequest):

    num_vists = request.session.get('num_vists', 0)
    request.session['num_vists'] = num_vists + 1

    # number of book model
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # available books
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    # context to send to the template
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_vists,
    }
    return render(request, 'catalog/index.html', context=context)

class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    template_name = 'catalog/book_list.html'
    context_object_name = 'book_list'
    paginate_by = 3

    def get_queryset(self):
        return Book.objects.all().order_by('title')

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'
    context_object_name = 'book'

class AuthorListView(generic.ListView):
    model = Author
    template_name = 'catalog/author_list.html'
    context_object_name = 'author_list'
    paginate_by = 2

class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'
    context_object_name = 'author'

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class BorrowedBookListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

# the order of decorator matters
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request: HttpRequest, pk: int):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    borrower = book_instance.borrower

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.borrower = borrower
            book_instance.save()

            return HttpResponseRedirect(reverse('catalog:all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/renew_book.html', context=context)

class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.add_author'
    form_class = AuthorForm
    model = Author
    template_name = 'catalog/author_form.html'
    success_url = reverse_lazy('catalog:authors')

class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.change_author'
    form_class = AuthorForm
    model = Author
    template_name = 'catalog/author_form.html'
    success_url = reverse_lazy('catalog:authors')

class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.delete_author'
    model = Author
    template_name = 'catalog/author_confirm_delete.html'
    success_url = reverse_lazy('catalog:authors')

class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.add_book'
    form_class = BookForm
    model = Book
    success_url = reverse_lazy('catalog:books')
    template_name = 'catalog/book_create.html'

class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.change_book'
    form_class = BookForm
    model = Book
    success_url = reverse_lazy('catalog:books')
    template_name = 'catalog/book_create.html'

class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.delete_book'
    model = Book
    success_url = reverse_lazy('catalog:books')
    template_name = 'catalog/book_confirm_delete.html'

@login_required
def borrow_book(request: HttpRequest, pk: int):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    borrowed_book = BookInstance.objects.filter(borrower=request.user).values_list('book__title', flat=True)
    if book_instance.book.title in borrowed_book:
        messages.warning(request, 'You already borrowed this book')
        return HttpResponseRedirect(reverse('catalog:my-borrowed'))
    book_instance.borrower = request.user
    book_instance.due_back = datetime.date.today() + datetime.timedelta(weeks=3)
    book_instance.status = 'o'
    book_instance.save()
    # use django message framework for success message
    messages.success(request, 'You have successfully borrowed this book')
    return HttpResponseRedirect(reverse('catalog:my-borrowed'))

class AvilableBooksListView(LoginRequiredMixin, generic.ListView):
    template_name = 'catalog/avilable_books.html'
    context_object_name = 'book_list'
    model = BookInstance
    paginate_by = 3


    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='a').values('book__id', 'book__title').annotate(count=Count('book__title')).order_by('book__title')

@login_required
def return_book(request:HttpRequest, pk:int):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    book_instance.borrower = None
    book_instance.due_back = None
    book_instance.status = 'a'
    book_instance.save()
    messages.success(request, 'You have successfully returned this book')
    return HttpResponseRedirect(reverse('catalog:my-borrowed'))

class BookInstanceCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.add_bookinstance'
    form_class = BookInstanceForm
    model = BookInstance
    template_name = 'catalog/bookinstance_create.html'
    success_url = reverse_lazy('catalog:books')

    # pass message to view
    def form_valid(self, form):
        messages.success(self.request, 'You have successfully created a new book instance')
        return super().form_valid(form)

templates/catalog/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Author: {{ author }}</h1>

{% if author.book_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for book in author.book_set.all %}
    <li><a href="{% url 'catalog:book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the author?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content%}
    <h1>Author Detail</h1>
    <h2><strong>First Name:</strong> {{ author.first_name }}</h2>
    <p><strong>Last Name:</strong>{{ author.last_name }}</p>
    <p><strong>DOB:</strong> {{ author.date_of_birth }}</p>
    <p><strong>DOD:</strong> {{ author.date_of_death }}</p>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>
    
        {% for book in author.books.all %}
          <hr />
          <h5><strong>Title:</strong> {{ book.title }}({{book.bookinstance_set.count}})</h5>
          <p><strong>Summary:</strong> {{ book.summary }}</p></p>
        {% endfor %}
      </div>
{% endblock  %}

templates/catalog/author_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
          <a href="{{ author.get_absolute_url }}"> {{ author.first_name }} {{ author.last_name }} </a>
           ({{author.books.count}}) 
          {% if perms.catalog.change_author %} 
            <a href="{% url 'catalog:author-update' author.id %}">Update</a> | 
          {% endif %} 
          {% if perms.catalog.delete_author %} 
             <!-- if we want to delete with out using template we must use form tag like below -->
            <!-- <form method="POST" action="{% url 'catalog:author-delete' author.id %}">
              {% csrf_token %}<input type="submit" value="DELETE">
            </form> -->
            <a href="{% url 'catalog:author-delete' author.id %}">Delete</a> 
          {% endif %}
        
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

templates/catalog/avilable_books.html
{% extends "base.html" %}

{% block content %}
    <h1>Avilable Book List</h1>
    {% if book_list %}
        <ul>
            {% for copy in book_list %}
                <li>
                    <a href="{% url 'catalog:book-detail' copy.book__id %}">{{copy.book__title}}</a> ({{copy.count}})
                </li>
            {% endfor %}
        </ul>
    {% else %}
      <p>There are no avilable books in the library.</p>
    {% endif %}       
{% endblock %}

templates/catalog/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Book: {{ author }}</h1>

    {% if book.bookinstance_set.all.count %}

        <p>You can't delete this book until all their books instance have been deleted:</p>
        <ul>
        {% for book in book.bookinstance_set.all %}
            <li><a href="{% url 'catalog:book-detail' book.book.id %}">{{book.id}}</a> </li>
        {% endfor %}
        </ul>

    {% else %}
        <p>Are you sure you want to delete the author?</p>
        <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete.">
        </form>
    {% endif %}

{% endblock %}

templates/catalog/book_create.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content%}
    <h1>Book Detail</h1>
    <h2><strong>Title: </strong> {{ book.title }}</h2>
    <p><strong>Author: </strong><a href="{{ book.author.get_absolute_url }}">{{ book.author.last_name }} {{ book.author.first_name }}</a></p>
    <p><strong>Summary: </strong> {{ book.summary }}</p>
    <p><strong>ISBN: </strong> {{ book.isbn }}</p>
    <p><strong>Genre: </strong> {{ book.genre.name }}</p> 
    <p><strong>Language: </strong> {{ book.language.name }}</p>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>
    
        {% for copy in book.bookinstance_set.all %}
          <hr />
          <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
          </p>
          <p class="text-primary">{% if copy.borrower.username == request.user.username %}You Borrowed it!{%endif%}</p>
          {% if copy.status != 'a' %}
            <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
          {% endif %}
          <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
          <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
          
          {% if copy.status == 'a' %}
            <form action="{% url 'catalog:book_borrow' copy.id %}" method="post">
              {% csrf_token %}
              <button type="submit">Borrow this book</button>
            </form>
          {% endif %}

        {% endfor %}
      </div>
{% endblock  %}

templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}><p>{{ message }}</p></li>
        {% endfor %}
      </ul>
    {% endif %}
    {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}}) |
        {% if perms.catalog.change_book %}
          <a href="{% url 'catalog:book-update' book.id %}">Edit</a>
        {% endif %} |
        {% if perms.catalog.delete_book %}
          <a href="{% url 'catalog:book-delete' book.id %}">Delete</a>
        {% endif %}
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

templates/catalog/bookinstance_create.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/catalog/bookinstance_list_borrowed.html
{% extends "base.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'catalog:book-detail' bookinst.book.id %}">{{bookinst.book.title}}</a> 
            ({{ bookinst.due_back }})- {{ bookinst.borrower }}
            {% if perms.catalog.can_mark_returned %}- 
              <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">Renew</a>  
            {% endif %}
        </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}><p>{{ message }}</p></li>
        {% endfor %}
      </ul>
    {% endif %}

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})

        <form method="POST" action="{% url 'catalog:book_return' bookinst.id %}">
          {% csrf_token %}<button class="btn btn-link" type="submit">Return</button>
        </form>

      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
<title>Home</title>
{% endblock %}
{% block content %}
<h1>Local Library Home</h1>
<p>
  Welcome to LocalLibrary, a website developed by
  <em>Us</em>!
</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
  <li><strong>Books:</strong> {{ num_books }}</li>
  <li><strong>Copies:</strong> {{ num_instances }}</li>
  <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
  <li><strong>Authors:</strong> {{ num_authors }}</li>
  <li><strong>Authors:</strong> {{ num_authors }}</li>
  <li><strong>Genres:</strong> {{ num_genres }}</li>
</ul>
<p>
  You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>
{% endblock %}

templates/catalog/renew_book.html
{% extends "base.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}